# Generated by Django 3.2 on 2021-04-06 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('subtitle', models.CharField(max_length=63)),
            ],
        ),
        migrations.AddField(
            model_name='instagramportfolio',
            name='alt_image',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagramportfolio',
            name='label_link',
            field=models.CharField(default='', max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instagramportfolio',
            name='image',
            field=models.ImageField(upload_to='images/portfolio/'),
        ),
        migrations.AlterField(
            model_name='instagramportfolio',
            name='subtitle',
            field=models.CharField(max_length=63),
        ),
        migrations.CreateModel(
            name='WorkPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('image', models.ImageField(upload_to='images/portfolio/')),
                ('alt_image', models.TextField(max_length=255)),
                ('link', models.URLField()),
                ('label_link', models.CharField(max_length=63)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=63)),
                ('subtitle', models.CharField(max_length=63)),
                ('description', models.TextField(max_length=255)),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.work')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MuggumPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('image', models.ImageField(upload_to='images/portfolio/')),
                ('alt_image', models.TextField(max_length=255)),
                ('link', models.URLField()),
                ('label_link', models.CharField(max_length=63)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=63)),
                ('subtitle', models.CharField(max_length=63)),
                ('description', models.TextField(max_length=255)),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.work')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
