# Generated by Django 3.2 on 2021-04-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_auto_20210406_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramportfolio',
            name='homepage',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muggumportfolio',
            name='homepage',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workportfolio',
            name='homepage',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
