# Generated by Django 3.2 on 2021-04-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_auto_20210408_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramportfolio',
            name='subtitle',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='muggumportfolio',
            name='subtitle',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='workportfolio',
            name='subtitle',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
