# Generated by Django 3.2 on 2021-04-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_auto_20210408_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramportfolio',
            name='insta_id',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
