# Generated by Django 3.2 on 2021-08-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_instagramportfolio_insta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramportfolio',
            name='energy',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='instagramportfolio',
            name='planet_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('big', 'Big')], default='small', max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='muggumportfolio',
            name='energy',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='muggumportfolio',
            name='planet_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('big', 'Big')], default='small', max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='workportfolio',
            name='energy',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workportfolio',
            name='planet_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('big', 'Big')], default='small', max_length=63, null=True),
        ),
    ]
