# Generated by Django 3.2.9 on 2021-11-10 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_auto_20210804_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramportfolio',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='muggumportfolio',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='workportfolio',
            name='homepage',
        ),
    ]
