# Generated by Django 3.2 on 2022-01-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_auto_20220110_1828'),
        ('identity', '0009_auto_20220111_1716'),
    ]

    operations = [
    ]
