# Generated by Django 3.2 on 2021-08-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arteablog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.AddField(
            model_name='article',
            name='astral_article',
            field=models.TextField(default='', max_length=4095),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='astral_cover',
            field=models.ImageField(null=True, upload_to='astral/blog/article/covers/'),
        ),
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(null=True, upload_to='blog/article/covers/'),
        ),
    ]
