# Generated by Django 3.2.9 on 2021-11-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arteablog', '0002_auto_20210805_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='astral_cover',
            field=models.ImageField(null=True, upload_to='astral/blog/category/covers/'),
        ),
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.ImageField(null=True, upload_to='blog/category/covers/'),
        ),
    ]
