# Generated by Django 3.2.9 on 2021-11-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arteablog', '0003_auto_20211110_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='astral_cover',
        ),
    ]
